refactor: 통합 테스트 제거
team-reflog/reflog-server pull request #43
Opened 2024-01-07 11:32 UTC by whatasame

## 👻 작업 요약

통합 테스트를 제거하였습니다.

## ⚒️ 작업 내용

* 클라이언트의 요청에 해당하는 row가 데이터베이스에 없을 경우 GlobalException을 던지도록 변경
* 데이터베이스에 값을 가져와서 검증하는 로직은 도메인 컴포넌트로 이동

## 🎸 기타

데이터베이스에서 값을 가져와 검증하는 것은 도메인 로직이지만, 데이터베이스에 값이 없는 것은 요청 값이 잘못된 것으로 도메인 로직이 아니라고 판단하였습니다.

GlobalException에 대한 테스트가 필요합니다.

2024-01-07 12:54 UTC, whatasame commented on src/main/java/com/github/teamreflog/reflogserver/member/domain/MemberValidator.java
> +    }
PasswordEncoder.matches()를 mock으로 테스트하기 어려웠습니다. 또, 잘 만들어진 라이브러리를 테스트하는 것 같았는데요.

그래서 boolean에 따른 예외 여부만 별도로 추출하여 테스트했습니다. 괜찮나요?

2024-01-07 12:54 UTC, whatasame commented on src/main/java/com/github/teamreflog/reflogserver/auth/domain/JwtProvider.java
> +package com.github.teamreflog.reflogserver.auth.domain;
서비스에서 지정한 형식대로 JWT를 발급하고 검증하는 컴포넌트를 infrastructure가 아니라 domain이라고 판단하였습니다!

2024-01-07 15:21 UTC, rimrim990 reviewed
열일 하시네요 ^^

2024-01-07 15:21 UTC, rimrim990 commented on src/main/java/com/github/teamreflog/reflogserver/auth/domain/JwtProvider.java
> +package com.github.teamreflog.reflogserver.auth.domain;
저는 대부분의 로직이 외부 라이브러리에 의존하기 때문에 domain보다는 infra가 적절하다고 생각합니다!

2024-01-07 15:21 UTC, rimrim990 commented on src/main/java/com/github/teamreflog/reflogserver/auth/application/AuthService.java
> +                        .orElseThrow(ReflogIllegalArgumentException::new);
> 데이터베이스에서 값을 가져와 검증하는 것은 도메인 로직이지만, 데이터베이스에 값이 없는 것은 요청 값이 잘못된 것으로 도메인 로직이 아니라고 판단하였습니다

이것에 따라 domain과 common으로 exception 패키지를 나눈 건가요?

2024-01-07 15:31 UTC, whatasame commented on src/main/java/com/github/teamreflog/reflogserver/auth/application/AuthService.java
> +                        .orElseThrow(ReflogIllegalArgumentException::new);
넵! 원래는 java.lang에 있는 IllegalArgumentException을 던지려고 했으나 Exception handling에서 문제가 발생할 것 같아 별도의 이름을 지어주었습니다.

라이브러리나 java의 api에서 발생하는 IllegalArgumentException는 예상하지 못한 예외일 가능성이 높기 때문에 핸들링을 하면 안 된다고 생각합니다.

2024-01-07 15:31 UTC, whatasame commented on src/main/java/com/github/teamreflog/reflogserver/auth/domain/JwtProvider.java
> +package com.github.teamreflog.reflogserver.auth.domain;
오 그것도 맞네요. 그럼 domain에는 인터페이스를 두고 infrastructure에서 구현할까요? 그럴 가능성은 적지만 JWT 라이브러리가 바뀔 때 도메인의 변경 사항을 최소화 할 수 있을 것 같아요.

2024-01-08 03:36 UTC, bkRyusim requested changes
Application Layer 테스트를 없애니까 속이 시원하네요. boolean으로 한부분 멤버의 패스워드를 테스트 given에서 인코딩해서 넣는건 어떤가요

2024-01-08 03:36 UTC, bkRyusim commented on src/main/java/com/github/teamreflog/reflogserver/auth/domain/JwtProvider.java
> +package com.github.teamreflog.reflogserver.auth.domain;
저도 infrastructure로 들어가는게 나을 듯 합니다. 도메인 로직이라기엔 정밀하게 테스트하기도 까다롭고 외부 라이브러리를 연결하는 facade라고 생각합니다.

2024-01-08 03:36 UTC, bkRyusim commented on src/main/java/com/github/teamreflog/reflogserver/member/domain/MemberValidator.java
> +    }
위의 JwtProvider와 유사하게, PasswordEncoder도 외부 의존적인데, 클래스로 한번 감싸서 infrastructure에 두는것도 고려는 해볼 만 하겠네요. 

void를 따로 빼는 것이 좀 과해 보이는데, 테스트 시 Member를 생성할 때 encoding 된 패스워드를 넣는 방법은 어떤가요? 테스트 대상 멤버가 encoding된 패스워드를 가지고 있다는 스펙이 더 잘 드러날 것 같습니다.

```java
Member.of("email@email.com", passwordEncoder.encode("password"));
```

2024-01-08 04:01 UTC, whatasame reviewed
facade 패턴을 적용하여 JwtProvider를 domain에서 인터페이스로 정의하고 infrastructure에서 구현하도록 변경하였습니다.

2024-01-08 04:01 UTC, whatasame commented on src/main/java/com/github/teamreflog/reflogserver/member/domain/MemberValidator.java
> +    }
테스트에서 인코딩할 경우 MemberValidator 단위 테스트에서 PasswordEncoder의 구현체를 의존하게 되는데 괜찮을까요? 

mocking도 고려했으나 한 번 시작하면 나중에 mock 객체에 의존하는 경우가 많아질 것 같아 조심스럽습니다.

2024-01-08 06:57 UTC, bkRyusim commented on src/main/java/com/github/teamreflog/reflogserver/member/domain/MemberValidator.java
> +    }
테스트에서 PasswordEncoder를 의존하는게 걱정이라면 애초에 PasswordEncoder를 Application 레이어에서 의존하면 안된다고 생각합니다.

```java
// infrastructure
public class MemberPasswordEncoderImpl implements MemberPasswordEncoder {
    private final PasswordEncoder encoder;

    public MemberPassword encode(final String raw) {
        return MemberPassword.of(encoder.encode(raw));
    }
}

// domain
public interface MemberPasswordEncoder {
    MemberPassword encode(String rawPassword); 
}

// test
@Test
void testtest() {
    MemberValidator validator = new MemberValidator(..., raw -> raw + "aa");
    Member member = Member.of("email@email.com", "1234aa");
    assertThat(validator.validatesomething(member, "1234")).notthrowsexception()
    assertThat(validator.validatesomething(member, "134")).throwsexception()
}
```

의사코드 느낌으로 대충 짜본건데.. 이런 플로우도 생각해볼 것 같네요.

2024-01-08 14:12 UTC, bkRyusim approved these changes
비밀번호 match 부분만 나중에 더 연구해 봅시다

2024-01-08 14:15 UTC, merged